apiVersion: v1
kind: ReplicationController
metadata:
  name: node-app
spec:
  replicas: 3
  selector:
    app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: registry.gitlab.com/unrealengine/test_kuber:latest
        ports:
        - containerPort: 8080