apiVersion: v1
kind: Secret
metadata:
  name: registrypullsecret
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJyZWdpc3RyeS5naXQuZmxleC1zb2x1dGlvbi5jb20iOiB7CgkJCSJhdXRoIjogIlpDNTJiMlJ2Y0dsaGJtOTJPa1loWlhoRVpYWlBjSE15TURJeCIKCQl9LAoJCSJyZWdpc3RyeS5naXRsYWIuY29tIjogewoJCQkiYXV0aCI6ICJkVzV5WldGc1pXNW5hVzVsTkM0eE1TNHlRR2R0WVdsc0xtTnZiVHBrWVc1NVlUSTRNemMwTm0xaFpFYz0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson