apiVersion: v1
kind: Pod
metadata: 
  name: node-app
  labels:
    creation_mathod: manual
    env: prod
spec:
  containers:
  - image: registry.gitlab.com/unrealengine/test_kuber:latest
    name: node-app
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 15
    ports:
    - containerPort: 8080
      protocol: TCP
    resources:
      limits:
        memory: "1000Mi"
        cpu: "250m"
        